POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer tokenhere

{
    "title": "Add blog for Niko with Token Authorization",
    "author": "James",
    "url": "http://test//blog",
    "likes": 1,
    "userId": "64915361d8575733ada512d1"
}