POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "Niko",
    "name": "Niko K",
    "password": "salainen"
}

# {
#     "username": "uniikki",
#     "name": "uniikkityyppi",
#     "password": "ss"
# }